sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: "root"
    password: "0216"
  alioss:
    endpoint: "s3.ap-northeast-1.wasabisys.com"
    access-key-id: "00NIRRX1AF0Y3K37LXXL"
    access-key-secret: "osU04kucQrK1aMJI2sswz7PMiyoD3EmswzFSVm0w"
    bucket-name: "spring"
  redis:
    host: localhost
    port: 11112
    database: 1